### ISSUE TITLE
Reliability module crashes

### ISSUE THREAD

**Issue by SoFiA-Admin** [SoFiA-Admin/SoFiA#113] opened 2017-01-25 04:31 UTC
The reliability module crashes in a few situations where illegal user input is received. This should be fixed to ensure that the module prints an error message instead and exits gracefully rather than crashing.

**Situation 1:** There is no noise or no negative signal in the data. In the case, the rms measurement crashed with the following error message:

    Traceback (most recent call last):
      File "sofia_pipeline.py", line 344, in <module>
            globalrms=functions.GetRMS(np_Cube,rmsMode='negative',zoomx=1,zoomy=1,zoomz=1,verbose=True,sample=sampleRms)
      File "build/lib.linux-x86_64-2.7/sofia/functions.py", line 43, in GetRMS
        bins=np.arange(cubemin,abs(cubemin)/nrbins-1e-12,abs(cubemin)/nrbins)
    ValueError: Maximum allowed size exceeded
    Pipeline failed with exit code 1.

An example parameter file using wavelet reconstruction on the SoFiA test data cube is attached below:
[example_par_file_wavelet.txt](https://github.com/SoFiA-Admin/SoFiA/files/728626/example_par_file_wavelet.txt)

**Situation 2:** The reliability module also crashes if there are not enough sources. The error message in this case is the following:

    /usr/lib/python2.7/dist-packages/numpy/lib/function_base.py:1766: RuntimeWarning: invalid value encountered in true_divide
      return (dot(X, X.T.conj()) / fact).squeeze()
    build/lib.linux-x86_64-2.7/sofia/addrel.py:184: RuntimeWarning: invalid value encountered in greater_equal
      pseudoreliable=np.maximum(Rs,0)>=threshold
    # Working in parameter space [ n_pix snr_sum snr_max ]
    # Using a kernel with the shape of the covariance and size scaled by a factor 0.50.
    # The sqrt(kernel) size is:
    [[ nan  nan  nan]
     [ nan  nan  nan]
     [ nan  nan  nan]]
     iteration, median, width, median/width =   0,       nan,       nan,       nan
    build/lib.linux-x86_64-2.7/sofia/addrel.py:190: RuntimeWarning: invalid value encountered in greater_equal
      reliable=(np.maximum(Rs,0)>=threshold)*(data[pos,ftotCOL].reshape(-1,)>fMin)
    Traceback (most recent call last):
      File "sofia_pipeline.py", line 360, in <module>
        objects,reliable = addrel.EstimateRel(np.array(objects), outroot, catParNames, **Parameters['reliability'])
      File "build/lib.linux-x86_64-2.7/sofia/addrel.py", line 237, in EstimateRel
        plt.hist(delt/deltstd,bins=np.arange(deltmin/deltstd,max(5.1,deltmax/deltstd),0.01),cumulative=True,histtype='step',color='r',normed=True)
      File "/usr/lib/pymodules/python2.7/matplotlib/pyplot.py", line 2827, in hist
        stacked=stacked, **kwargs)
      File "/usr/lib/pymodules/python2.7/matplotlib/axes.py", line 8326, in hist
        m, bins = np.histogram(x[i], bins, weights=w[i], **hist_kwargs)
      File "/usr/lib/python2.7/dist-packages/numpy/lib/function_base.py", line 199, in histogram
        sa.searchsorted(bins[-1], 'right')]
    IndexError: index out of bounds

This looks like a problem in the recently added automatic kernel calculation, as the kernel parameters are all NaN. Again, an example parameter file running CNHI on the SoFiA test data cube is attached below:
[example_par_file_cnhi.txt](https://github.com/SoFiA-Admin/SoFiA/files/728648/example_par_file_cnhi.txt)

**Comment by paoloserra** [comment] 2017-04-10 21:53
I have made a few changes to deal with the issues reported here. With those changes, sofia_pipeline checks whether there are any negative sources and, if not, exits giving an error message and a few suggestions on how to proceed. This resolves "Situation 1" above, as if there are no negative voxels there can also not be negative sources. Furthermore, addrel.py exits if the automated kernel contains NaNs. This seems to happen when there are too few negative sources (e.g., 1). Again, SoFiA gives a hint on how the user could proceed.

This should cover several situations where things were not working. If there are additional ones that are still not covered please report them here.

**Comment by vdhulst** [comment] 2017-06-22 19:17
Fix works.  I ran SoFiA on a cube and set the threshold at 5 sigma so no negative sources were found. SoFiA exited gracefully, without producing output files, with the error message: 

ERROR: You asked SoFiA to calculate the reliability of the detected sources.
       Unfortunately, this calculation cannot be done because there are no
       negative sources in the catalogue of detections. This may occur because
       of your source-finding and/or filtering settings.
       Negative sources are strictly necessary to calculate the reliability.
       You can do one of the following:
       1) switch off the reliability calculation.
       2) modify the source-finding and/or filtering settings in order to detect
          negative sources.
Merging complete


--- 3.231 seconds since start
Pipeline failed with exit code 1.

**Comment by vdhulst** [comment] 2017-06-22 19:19
Sorry, accidentally closed the issue. This only took care of the reliability issue. The CNHI issue still exists.

**Comment by paoloserra** [comment] 2017-07-03 11:52
Could you post the error message you get?
 
Running SoFiA with the parameter file example_par_file_cnhi.txt I get the following:
 
> --- 78.478 seconds since start
> 
> --- SoFiA: Determining reliability ---
> # Working in parameter space [ n_pix snr_sum snr_max ]
> /usr/local/Cellar/python/2.7.2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/lib/function_base.py:2487: RuntimeWarning: Degrees of freedom <= 0 for slice
>   warnings.warn("Degrees of freedom <= 0 for slice", RuntimeWarning)
> /usr/local/Cellar/python/2.7.2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/lib/function_base.py:2496: RuntimeWarning: divide by zero encountered in double_scalars
>   c *= 1. / np.float64(fact)
> /usr/local/Cellar/python/2.7.2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/lib/function_base.py:2496: RuntimeWarning: invalid value encountered in multiply
>   c *= 1. / np.float64(fact)
> ERROR: The reliability cannot be calculated because the smoothing kernel
>        derived from 1 negative sources contains NaNs.
>        A good kernel is required to calculate the density field of positive
>        and negative sources in parameter space.
>        Try increase the number of negative sources by changing the source.
>        finding and/or filtering settings.

The user is told that the source finding / filtering steps result in 1 negative source, and that the resulting kernel is not valid.

Are you getting a different error?

**Comment by vdhulst** [comment] 2017-07-04 09:02
The error I get (with a graceful exit and without complaints from Python) is:

ERROR: You asked SoFiA to calculate the reliability of the detected sources.
       Unfortunately, this calculation cannot be done because there are no
       negative sources in the catalogue of detections. This may occur because
       of your source-finding and/or filtering settings.
       Negative sources are strictly necessary to calculate the reliability.
       You can do one of the following:
       1) switch off the reliability calculation.
       2) modify the source-finding and/or filtering settings in order to detect
          negative sources.
Merging complete

--- 7.902 seconds since start
Pipeline failed with exit code 1.

**Comment by paoloserra** [comment] 2017-09-25 08:24
OK, this is the intended behaviour. Closing this, please reopen if some other errors come up.

**Comment by SoFiA-Admin** [comment] 2017-10-23 06:10
The reliability module still crashes in certain situations, so I decided to re-open this issue. In my concrete example, I run the threshold finder with a 3σ threshold plus merging radii of 1 and minimum sizes of 5 in <var>x</var>, <var>y</var> and <var>z</var>. In this scenario, the reliability module crashes with the following error message:

    Traceback (most recent call last):
      File "/SoFiA/sofia_pipeline.py", line 389, in <module>
        objects, reliable = addrel.EstimateRel(np.array(objects), outroot, catParNames, **Parameters['reliability'])
      File "/SoFiA/build/lib.linux-x86_64-2.7/sofia/addrel.py", line 168, in EstimateRel
        Np = gaussian_kde_set_covariance(pars[:,pos], kernel)
      File "/SoFiA/build/lib.linux-x86_64-2.7/sofia/addrel.py", line 15, in __init__
        stats.gaussian_kde.__init__(self, dataset)
      File "/usr/lib/python2.7/dist-packages/scipy/stats/kde.py", line 188, in __init__
        self.set_bandwidth(bw_method=bw_method)
      File "/usr/lib/python2.7/dist-packages/scipy/stats/kde.py", line 498, in set_bandwidth
        self._compute_covariance()
      File "/SoFiA/build/lib.linux-x86_64-2.7/sofia/addrel.py", line 17, in _compute_covariance
        self.inv_cov = np.linalg.inv(self.covariance)
      File "/usr/lib/python2.7/dist-packages/numpy/linalg/linalg.py", line 520, in inv
        ainv = _umath_linalg.inv(a, signature=signature, extobj=extobj)
      File "/usr/lib/python2.7/dist-packages/numpy/linalg/linalg.py", line 90, in _raise_linalgerror_singular
        raise LinAlgError("Singular matrix")
    numpy.linalg.linalg.LinAlgError: Singular matrix
    Pipeline failed with exit code 1.

**Comment by ngiese** [comment] 2017-10-23 06:41
I cannot reproduce your error using the SoFiA test data cube. For me the pipeline terminates as expected with the correct error message (no negative sources found). Are you using the latest version of SoFiA? Is it possible to make your data (or part of it) available for testing?

**Comment by SoFiA-Admin** [comment] 2017-10-23 07:40
Interesting, I tested it again, and SoFiA definitely crashes when I use the threshold finder at 3σ. When I choose 2σ instead, everything runs fine, so I suspect that it has something to do with the number of negative detections. I use the very latest version of SoFiA (given that all of the most recent updates were uploaded by myself). The data cube is simply the SoFiA test data cube; is this the one you used as well?

**Comment by ngiese** [comment] 2017-10-23 07:55
Yes, I used the SoFiA test cube (from the Wiki). It runs fine for 2 sigma and exits as expected for 3 sigma.

**Comment by SoFiA-Admin** [comment] 2017-10-24 02:26
Thank you to @ngiese for fixing this problem by inserting a check whether the covariance matrix can be inverted and printing an error message if that’s not the case. I tested this solution, and it appears to work fine on my installation.

Unfortunately, it didn’t take much effort to crash the reliability module again, so there are more issues with insufficient checking of the input data in this module. All it needs for crashing it again is to change the threshold of the threshold finder from 3 to 2.9. In this case, SoFIA will first print a lot of runtime warnings:

    /SoFiA/build/lib.linux-x86_64-2.7/sofia/addrel.py:18: RuntimeWarning: invalid value encountered in sqrt
      self._norm_factor = np.sqrt(np.linalg.det(2*np.pi*self.covariance)) * self.n
    /usr/lib/python2.7/dist-packages/scipy/stats/kde.py:231: RuntimeWarning: overflow encountered in exp
      result = result + exp(-energy)
    /usr/lib/python2.7/dist-packages/scipy/stats/kde.py:238: RuntimeWarning: overflow encountered in exp
      result[i] = sum(exp(-energy), axis=0)
    /SoFiA/build/lib.linux-x86_64-2.7/sofia/addrel.py:206: RuntimeWarning: invalid value encountered in greater_equal
      pseudoreliable = np.maximum(Rs, 0) >= threshold

and then later crash with the following error message:

    /SoFiA/build/lib.linux-x86_64-2.7/sofia/addrel.py:212: RuntimeWarning: invalid value encountered in greater_equal
      reliable = (np.maximum(Rs, 0) >= threshold) * (data[pos, ftotCOL].reshape(-1,) > fMin)
    Traceback (most recent call last):
      File "/SoFiA/sofia_pipeline.py", line 389, in <module>
        objects, reliable = addrel.EstimateRel(np.array(objects), outroot, catParNames, **Parameters['reliability'])
      File "/SoFiA/build/lib.linux-x86_64-2.7/sofia/addrel.py", line 259, in EstimateRel
        plt.hist(delt / deltstd, bins=np.arange(deltmin / deltstd, max(5.1, deltmax / deltstd), 0.01), cumulative=True, histtype='step', color='r', normed=True)
      File "/usr/lib/pymodules/python2.7/matplotlib/pyplot.py", line 2827, in hist
        stacked=stacked, **kwargs)
      File "/usr/lib/pymodules/python2.7/matplotlib/axes.py", line 8326, in hist
        m, bins = np.histogram(x[i], bins, weights=w[i], **hist_kwargs)
      File "/usr/lib/python2.7/dist-packages/numpy/lib/function_base.py", line 199, in histogram
        sa.searchsorted(bins[-1], 'right')]
    IndexError: index out of bounds
    Pipeline failed with exit code 1.

**Comment by SoFiA-Admin** [comment] 2017-10-24 02:32
And there’s more: if you set the threshold to 2.85, the following happens:

    Traceback (most recent call last):
      File "/SoFiA/sofia_pipeline.py", line 389, in <module>
        objects, reliable = addrel.EstimateRel(np.array(objects), outroot, catParNames, **Parameters['reliability'])
      File "/SoFiA/build/lib.linux-x86_64-2.7/sofia/addrel.py", line 259, in EstimateRel
        plt.hist(delt / deltstd, bins=np.arange(deltmin / deltstd, max(5.1, deltmax / deltstd), 0.01), cumulative=True, histtype='step', color='r', normed=True)
    MemoryError
    Pipeline failed with exit code 1.

**Comment by RussellJurek** [comment] 2017-10-24 02:34
That looks like some standard range checking for zeros and infinities will
deal with most of that.

**Comment by ngiese** [comment] 2017-10-25 00:32
> And there’s more: if you set the threshold to 2.85, the following happens:
> 
> Traceback (most recent call last):
>   File "/SoFiA/sofia_pipeline.py", line 389, in <module>
>     objects, reliable = addrel.EstimateRel(np.array(objects), outroot, catParNames, **Parameters['reliability'])
>   File "/SoFiA/build/lib.linux-x86_64-2.7/sofia/addrel.py", line 259, in EstimateRel
>     plt.hist(delt / deltstd, bins=np.arange(deltmin / deltstd, max(5.1, deltmax / deltstd), 0.01), cumulative=True, histtype='step', color='r', normed=True)
> MemoryError
> Pipeline failed with exit code 1.

I added another condition (deltmed / deltstd > -100) taken from line 222, where the same operation that failed here is performed.

**Comment by SoFiA-Admin** [comment] 2017-10-25 03:03
Thanks, that appears to have fixed the plotting issue. However, the module still crashes at a threshold of 2.9, but now with a different error message. Here is the full output from the reliability module:

    --- SoFiA: Determining reliability
    /SoFiA/build/lib.linux-x86_64-2.7/sofia/addrel.py:18: RuntimeWarning: invalid value encountered in sqrt
      self._norm_factor = np.sqrt(np.linalg.det(2*np.pi*self.covariance)) * self.n
    /usr/lib/python2.7/dist-packages/scipy/stats/kde.py:231: RuntimeWarning: overflow encountered in exp
      result = result + exp(-energy)
    /usr/lib/python2.7/dist-packages/scipy/stats/kde.py:238: RuntimeWarning: overflow encountered in exp
      result[i] = sum(exp(-energy), axis=0)
    /SoFiA/build/lib.linux-x86_64-2.7/sofia/addrel.py:206: RuntimeWarning: invalid value encountered in greater_equal
      pseudoreliable = np.maximum(Rs, 0) >= threshold
    /SoFiA/build/lib.linux-x86_64-2.7/sofia/addrel.py:212: RuntimeWarning: invalid value encountered in greater_equal
      reliable = (np.maximum(Rs, 0) >= threshold) * (data[pos, ftotCOL].reshape(-1,) > fMin)
    # Working in parameter space [ n_pix snr_sum snr_max ]
    # Using a kernel with the shape of the covariance and size scaled by a factor 0.50.
    # The sqrt(kernel) size is:
    [[ 0.05921704  0.05998864  0.00702913]
     [ 0.05998864  0.06077029  0.00712071]
     [ 0.00702913  0.00712071  0.00083436]]
     iteration, median, width, median/width =   0,       nan,       nan,       nan
    Traceback (most recent call last):
      File "/SoFiA/sofia_pipeline.py", line 389, in <module>
        objects, reliable = addrel.EstimateRel(np.array(objects), outroot, catParNames, **Parameters['reliability'])
      File "/SoFiA/build/lib.linux-x86_64-2.7/sofia/addrel.py", line 327, in EstimateRel
        Np = gaussian_kde_set_covariance(parsp[:,pos], setcov)
      File "/SoFiA/build/lib.linux-x86_64-2.7/sofia/addrel.py", line 15, in __init__
        stats.gaussian_kde.__init__(self, dataset)
      File "/usr/lib/python2.7/dist-packages/scipy/stats/kde.py", line 188, in __init__
        self.set_bandwidth(bw_method=bw_method)
      File "/usr/lib/python2.7/dist-packages/scipy/stats/kde.py", line 498, in set_bandwidth
        self._compute_covariance()
      File "/SoFiA/build/lib.linux-x86_64-2.7/sofia/addrel.py", line 17, in _compute_covariance
        self.inv_cov = np.linalg.inv(self.covariance)
      File "/usr/lib/python2.7/dist-packages/numpy/linalg/linalg.py", line 520, in inv
        ainv = _umath_linalg.inv(a, signature=signature, extobj=extobj)
      File "/usr/lib/python2.7/dist-packages/numpy/linalg/linalg.py", line 90, in _raise_linalgerror_singular
        raise LinAlgError("Singular matrix")
    numpy.linalg.linalg.LinAlgError: Singular matrix
    Pipeline failed with exit code 1.

I added another check at that position in the code to ensure that SoFiA exits gracefully and prints out a helpful message with instruction on how to resolve the problem.

**Comment by RussellJurek** [comment] 2017-10-25 03:43
Does numpy have a singular value decomposition method? It's a fair whack
slower than gauss-jordan elimination and LU decomposition, but it doesn't
fall over when it encounters a singular matrix. Instead it generates a
inverse for the invertible matrix that most closely approximates the
singular input matrix.

**Comment by SoFiA-Admin** [comment] 2017-10-25 03:45
I don’t know, but I would nevertheless prefer to terminate the pipeline if a sensible reliability estimate is not possible due to lack of negative detections.

**Comment by SoFiA-Admin** [comment] 2017-10-25 04:03
Just as a general summary, it looks like there are currently no appropriate sanity checks throughout the reliability module. My suggestion would be to systematically review this module in the future to come up with a sensible set of checks in the appropriate places, rather than the botch-up we have been doing so far. Overall, this issue will not need to hold up the release of SoFiA 1.1, as the outcome (termination of the pipeline for insufficient negative detections) will be the same anyway, although this does not occur in a particularly graceful way at the moment.

I will leave this issue open for now, so we can address this problem in the future and add to the discussion above.

**Comment by RussellJurek** [comment] 2017-10-25 04:45
Sounds reasonable to me.

**Comment by paoloserra** [comment] 2018-11-11 10:00
Please report individual errors when you find them so they can be fixed.

**Closed by paoloserra** 2018-11-11 10:00 UTC
Labels: bug
