### ISSUE TITLE
WCS conversion failure

### ISSUE THREAD

**Issue by SoFiA-Admin** [SoFiA-Admin/SoFiA#149] opened 2018-10-12 05:41 UTC
A user was trying to run SoFiA on the official test data cube and encountered a WCS conversion failure. Apart from the WCS failure, the pipeline was running fine. The relevant warning messages are attached below:

```
Writing XML catalogue: ~/Downloads/sofiatest/sofiatestcube_cat.xml.
Writing ASCII catalogue: ~/Downloads/sofiatest/sofiatestcube_cat.ascii.
WARNING: CELLSCAL keyword with value of 1/F found.
         Will regrid masked cube before making moment images.
WARNING: FITSFixedWarning: 'celfix' made the change 'Success'. [astropy.wcs.wcs]
WARNING: CELLSCAL keyword with value of 1/F found.
         Will account for varying pixel scale in WCS coordinate calculation.
WARNING: WCS conversion of parameters failed.
```

As the user was running the latest versions of Astropy (v3.0.2), my suspicion is that yet another incompatibility has been introduced into the new Astropy version 3. We will need to check the Astropy release notes to figure out what could have caused the issue.

**Comment by SoFiA-Admin** [comment] 2018-10-12 05:52
Now that’s interesting! This is the preamble of the user’s SoFiA output:

```
    Using: SoFiA   1.2.1-beta
           Python  3.6.5
           NumPy   1.14.3
           SciPy   1.1.0
           Astropy 3.0.2
```

The user apparently runs SoFiA on Python 3 (with success, I presume)! I only noticed this because the release notes for Astropy 3 mention right at the start that Python 2.7 is no longer supported! I wonder if this has something to do with the WCS failure. While I have converted most of the code such that it will run on either Python 2.7 or 3, there are still a few things that need to be checked and potentially updated, in particular integer division.

**Comment by paoloserra** [comment] 2019-10-11 10:49
I know this was a long time ago, but could that test be repeated now that we write out the actual error encountered during WCS conversion?

https://github.com/SoFiA-Admin/SoFiA/blob/38d20ab0c9c1dae35ddda7e8ea2272ccd318a589/sofia/wcs_coordinates.py#L232-L233

**Comment by vdhulst** [comment] 2019-10-16 08:21
Using: SoFiA   1.3.1
           Python  3.7.3
           NumPy   1.16.4
           SciPy   1.3.0
           Astropy 3.2.1

the error is:
WARNING: CELLSCAL keyword with value of 1/F found.
         Will regrid masked cube before making moment images.
WARNING: FITSFixedWarning: 'celfix' made the change 'Success'. [astropy.wcs.wcs]
WARNING: CELLSCAL keyword with value of 1/F found.
         Will account for varying pixel scale in WCS coordinate calculation.
WARNING: WCS conversion of parameters failed with the following error:
WARNING:   (<class 'NameError'>, NameError("name 'xrange' is not defined"), <traceback object at 0x1a1c911dc8>)
 
Running under Python 2.7.16 and Astropy 2.0.9 produces the same warnings but no conversion error.

**Comment by paoloserra** [comment] 2019-10-16 12:33
Thank you @vdhulst . Can you please check that following https://github.com/SoFiA-Admin/SoFiA/commit/72ba106f35d8723540ac402e4e5dbf22503afa60 the current master branch solves this problem?

**Comment by paoloserra** [comment] 2019-10-16 13:59
Great!

The warning messages are normal, they have always been there and have no consequences for the running of SoFiA.

We can close this issue then, and wait for Julia's test for https://github.com/SoFiA-Admin/SoFiA/issues/162 .

**Closed by paoloserra** 2019-10-16 13:59 UTC
Labels: bug

**Comment by vdhulst** [comment] 2019-10-16 14:16
@paoloserra: there still may be a small problem. Rather than the testcube I ran SoFiA on a WHISP fits file. SoFiA under python3 does not crash but gives the following error:
-----
WARNING: WCS conversion of parameters failed with the following error:
WARNING:   (<class 'TypeError'>, TypeError('expected bytes, str found'), <traceback object at 0x1a17e1c348>)
-----
Running SoFiA with the same parameters under python2 gives different warnings:
-----
WARNING: FITSFixedWarning: DATE-OBS= 1995.804 
a string value was expected. [sofia.wcs_coordinates]
WARNING: FITSFixedWarning: END 
keyrecords following the END keyrecord were ignored. [sofia.wcs_coordinates]
-----

**Comment by paoloserra** [comment] 2019-10-16 14:19
Interesting. This is probably a different problem than the one originally reported. Should we have a separate issue on this one?

**Comment by vdhulst** [comment] 2019-10-16 14:23
yes, that may be better. Let me first run SoFiA on a number of different cubes to make sure how often this happens. It does not crash, so it is not so vital. It has to do with writing proper FITS or understanding proper FITS so the error could be in the FITS file or in Astropy's interpretation of the FITS header.

**Comment by vdhulst** [comment] 2019-10-20 19:56
ran SoFiA (the python3 version) on FITS files produced by AIPS, MIRIAD, GIPSY and CASA. Only the GIPSY fits files give an unusual WCS warning: 
_WARNING: WCS conversion of parameters failed with the following error:
WARNING:   (<class 'TypeError'>, TypeError('expected bytes, str found'), <traceback object at 0x1a1d3fc308>)_
None of the FITS files causes SoFiA to crash. I used:
           SoFiA   1.3.1
           Python  3.7.3
           NumPy   1.16.4
           SciPy   1.3.0
           Astropy 3.2.1

**Comment by vdhulst** [comment] 2019-10-21 14:22
ran the new code. The error occurs on line 129 of sofia/wcs_coordinates.py
The entire log message is:
_GIPSY header found. Trying to convert to FITS standard.
Header repaired successfully.
WARNING: WCS conversion of parameters failed with the following error:
WARNING:   (<class 'TypeError'>, TypeError('expected bytes, str found'), <traceback object at 0x1a1f6005c8>)
WARNING:   at line 129 of wcs_coordinates.py_

**Comment by paoloserra** [comment] 2019-10-21 14:29
Right, as suspected that's the bit of code specific to GIPSY headers.

https://github.com/SoFiA-Admin/SoFiA/blob/256bb5f50422052eb87ba46a17e0c3716f7eaec4/sofia/wcs_coordinates.py#L129

It's be good to verify whether the issue is `str(header)` or `Wcsprm()` . Maybe break that line in two to see which operation is causing the issue?

**Comment by vdhulst** [comment] 2019-10-21 15:07
yes I think that is a good idea. Will give it a try.

**Comment by vdhulst** [comment] 2019-10-27 17:59
Split the statement as suggested and discovered that the problem is Wcsprm().
Did print the header array and it looks OK to me. The fix_gipsy_header(header) operation did change DEGREE into deg, HZ into Hz and FREQ-OHEL into FREQ.

**Comment by vdhulst** [comment] 2019-11-07 11:08
fixed the python 3.7 problem by encoding the fits header from a string to bytes and tested it both under python 3.7 and python 2.7. SoFiA runs without returning any wcs warnings. The log states:  _GIPSY header found. Trying to convert to FITS standard.
Header repaired successfully.
WCS coordinates added to catalogue._

**Comment by paoloserra** [comment] 2019-11-07 11:14
Great!!! Thanks @vdhulst !

**Comment by vdhulst** [comment] 2019-11-07 11:23
also added a few lines converting the content of DATE-OBS into a string, which is expected. I encountered that in GIPSY fits files it is a number while WCS expects a string (line 106-110).
