### ISSUE TITLE
Invalid sqrt encountered in gaussian_kde_set_covariance calculation

### ISSUE THREAD

**Issue by sam6321** [SoFiA-Admin/SoFiA#129] opened 2017-12-20 02:09 UTC
During the covariance calculations in addrel.py, I've noticed `np.linalg.det` will sometimes generate negative determinants for certain inputs.

For example, using a slightly modified `gaussian_kde_set_covariance` class that prints out the determinant values:

```python
class gaussian_kde_set_covariance(stats.gaussian_kde):
	def __init__(self, dataset, covariance):
		self.covariance = covariance
		stats.gaussian_kde.__init__(self, dataset)
	def _compute_covariance(self):
		self.inv_cov = np.linalg.inv(self.covariance)
		det = np.linalg.det(2*np.pi*self.covariance) # Added
		print "Det: {0}".format(det) # Added
		self._norm_factor = np.sqrt(det) * self.n
```
I get the following output (truncated to only show the relevant errors) when running SoFiA on [these input files.](https://www.dropbox.com/s/tgf8cdhwmr1mbdz/sofia_run_169.zip?dl=0)

```
...
--- 24.098 seconds since start
--- SoFiA 1.2.0-beta: Determining reliability
# Working in parameter space [ n_pix  snr_sum  snr_max ]
break now
# Using a kernel with the shape of the covariance and size scaled by a factor 0.50.
# The sqrt(kernel) size is:
[[0.06837953 0.05493453 0.04311652]
 [0.05493453 0.06198636 0.02390937]
 [0.04311652 0.02390937 0.03078024]]

/home/sam/SoFiA/build/lib.linux-x86_64-2.7-pydebug/sofia/addrel.py:21: RuntimeWarning: invalid value encountered in sqrt
  self._norm_factor = np.sqrt(det) * self.n

Det: -3.03336264461e-22
Det: -3.03336264461e-22

/home/sam/SoFiA/python_env/lib/python2.7/site-packages/scipy-1.1.0.dev0+4019b40-py2.7-linux-x86_64.egg/scipy/stats/kde.py:215: RuntimeWarning: overflow encountered in exp
  result = result + exp(-energy)

/home/sam/SoFiA/python_env/lib/python2.7/site-packages/scipy-1.1.0.dev0+4019b40-py2.7-linux-x86_64.egg/scipy/stats/kde.py:222: RuntimeWarning: overflow encountered in exp
  result[i] = sum(exp(-energy), axis=0)

/home/sam/SoFiA/build/lib.linux-x86_64-2.7-pydebug/sofia/addrel.py:212: RuntimeWarning: invalid value encountered in greater_equal
  pseudoreliable = np.maximum(Rs, 0) >= threshold

/home/sam/SoFiA/build/lib.linux-x86_64-2.7-pydebug/sofia/addrel.py:218: RuntimeWarning: invalid value encountered in greater_equal
  reliable = (np.maximum(Rs, 0) >= threshold) * (data[pos, ftotCOL].reshape(-1,) > fMin)

 iteration, median, width, median/width =   0,       nan,       nan,       nan
The following sources have been detected: []

/home/sam/SoFiA/python_env/lib/python2.7/site-packages/numpy-1.15.0.dev0+356b481-py2.7-linux-x86_64.egg/numpy/lib/function_base.py:4033: RuntimeWarning: Invalid value encountered in median
  r = func(a, **kwargs)
...
```
The negative determinants, when fed in to `np.sqrt`, cause the calculated `Nps`, `Nns`, `nNps`, and `nNns` values (starting line 192 in addrel.py) to contain arrays of nans which just propagate throughout the rest of the calculations.

Is this the intended behaviour for this case, or would it be more appropriate to handle these errors differently, possibly with an early out if the input is not valid?

**Comment by SoFiA-Admin** [comment] 2017-12-20 07:20
Thanks for reporting these errors. The lack of sanity checks in the reliability calculation module (`addrel.py`) is a known problem and has been discussed extensively in a separate issue #113. Depending on how recent your SoFiA version is, some of the missing checks may have been added in the meantime, but there are still a few outstanding issues with that module even in the latest development version of SoFiA. I would not be too concerned about this at the moment, as negative determinants usually occur whenever there is an insufficient number of negative detections, in which case the particular set of parameter settings is unlikely to have produced meaningful results and should be discarded anyway.

**Comment by SoFiA-Admin** [comment] 2018-01-09 03:44
I will mark this issue as a duplicate of #113 to focus the discussion in a single location. Feel free to re-open if you think there is reason to keep this discussion separate.

**Closed by SoFiA-Admin** 2018-01-09 03:44 UTC
Labels: duplicate
