### ISSUE TITLE
A bug encountered during installation

### ISSUE THREAD

**Issue by astroXiao** [SoFiA-Admin/SoFiA#169] opened 2019-12-31 09:07 UTC
My laptop is Macbook Pro and I encountered an error when I was trying to install SoFiA 1.3.0
In fact there are two warnings and one error, shown below:

`warning: include path for stdlibc++ headers not found; pass '-stdlib=libc++' on
      the command line to use the libc++ standard library instead
      [-Wstdlibcxx-not-found]`

`/Users/altair_xiao/anaconda3/lib/python3.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: 
      "Using deprecated NumPy API, disable it with "          "#define
      NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
#warning "Using deprecated NumPy API, disable it with " \`

`src/linker/linker.cpp:241:10: fatal error: 'vector' file not found
#include <vector>
         ^~~~~~~~
2 warnings and 1 error generated.
error: command 'gcc' failed with exit status 1`

I don't know how to solve this problem. Xcode is installed on my Mac so gcc is actually clang. I don't know if this is the point. Thanks for any suggestions!

**Comment by RussellJurek** [comment] 2019-12-31 12:25
Hi,
    what version of OS X are you using? From 10.14 (OS X Mojave) onwards,
Apple no longer bundles the ANSI standard C headers in the expected
location. They need to be installed using a .pkg that's installed when you
install the xcode command line tools.

Please try the following, and then try installing SoFiA again.

1. Install Xcode from the app store.
2. Install xcode command line tools using the following command in a
terminal,
$ xcode-select --install
3. Install the system headers, which includes the C std system headers,
into the old location. You can do this using a package that is installed
along with the command line tools,

   1. $cd /Library/Developer/CommandLineTools/Packages/
   2. $open .
   3. Double-click the ,pkg that opens and install using the defaults.

Cheers,
Russell

**Comment by astroXiao** [comment] 2020-01-01 03:56
Hi Russell,

Thanks for your reply. I tried your instruction and failed again with the same problem. 
My Xcode is installed from the App Store, but it is not updated since installation (2019.9).
I used the command “Xcode-select —install” and it said the command line tools are
already installed. Then I installed the package and tried to install SoFiA again and 
encountered the same error. Do I need to uninstall Xcode and install it again?

P.S. My Mac is 10.14.5 Mojave

Happy New Year,
Xiao

**Comment by SoFiA-Admin** [comment] 2020-01-06 01:31
@astroXiao Thank you for reporting the SoFiA installation issue. The issue came to our attention a few weeks ago when others experienced the same problem (see issue #162 for details). We eventually tracked it down to a problem with Cython on the latest version of MacOS that resulted in our Cython code not compiling any longer.

We believe that we have fixed this problem in the latest development version of SoFIA. Please download the latest version from https://github.com/SoFiA-Admin/SoFiA/archive/master.zip and try to install on your computer. This should hopefully resolve the issue. If not, please let me know so we can investigate further.

**Comment by astroXiao** [comment] 2020-01-06 03:03
Hi @SoFiA-Admin ,

Thanks for your help. Using the latest version, the original problem is fixed. But another error occurred: 
`fatal error: 'ios' file not found`

And I found the below command can solve this problem:
`sudo CFLAGS="-mmacosx-version-min=10.14" python setup.py build --force`

Someone gives an explanation of this command in this issue:
[https://github.com/flier/pyfasthash/issues/28](url)

Finally I successfully installed SoFiA, although with a lot of warnings.

**Comment by SoFiA-Admin** [comment] 2020-01-06 03:20
@astroXiao Thank you for trying the newest SoFiA version. I am pleased to hear that you were able to successfully install the latest version on your computer. Don’t worry about all the warnings, they are normal and expected and should not affect the installation in any way.

The other problem about the `'ios' file not found` is interesting and new to me. Thanks for reporting that problem and the solution for resolving it. We will investigate the cause of that problem and might update the installation instructions to ensure that other users running into the same issue know what to do.

I will close this issue now, as the original problem appears to have been resolved.

**Closed by SoFiA-Admin** 2020-01-06 03:20 UTC
